# Print

In [1]:
print('hello')

hello


In [2]:
print("hello")

hello


In [4]:
print("""
    hello
    2024
    hello"""
)


    hello
    2024
    hello


In [6]:
x = 7

In [7]:
type(x)

int

In [8]:
x='aaa'

In [9]:
type(x)

str

In [16]:
x=8;
y=0



In [17]:
x,y=1,2


In [18]:
x+y

3

In [19]:
x-y

-1

In [20]:
2**3

8

In [23]:
(3/2)

1

In [35]:
q=150

In [27]:
print(q)

200


In [39]:
if q >300 or q < 200 :
    
    print('x')
    print(q)
    
else:
    print(q)

x
150


In [42]:
t=(1,2,3,4,5)

In [43]:
type(t)

tuple

In [44]:
t

(1, 2, 3, 4, 5)

In [45]:
l=[1,2,3,4,5]

In [46]:
type(l)

list

In [47]:
l.append(5)

In [48]:
l

[1, 2, 3, 4, 5, 5]

In [49]:
l.pop(0)

1

In [50]:
l

[2, 3, 4, 5, 5]

In [51]:
l.pop()

5

In [52]:
l.pop(-1)

5

In [57]:
d={'name':'ahmed',
  'number':125415}

In [58]:
d

{'name': 'ahmed', 'number': 125415}

In [60]:
d['number']

125415

In [61]:
l=[1,2,3,4]

In [63]:
range(5)

range(0, 5)

In [66]:

for i in range(len(l)):
    print(l[i])

1
2
3
4


In [67]:
w=10
while w < 20 :
    print(w)
    w+=1

10
11
12
13
14
15
16
17
18
19


In [76]:
def main(x,y):
    return x+y

In [77]:
main(1,2)

3

In [78]:
import numpy as np

In [91]:
x=np.array([[1,2,3],
           [4,5,6]])

In [92]:
type(x)

numpy.ndarray

In [93]:
x.shape

(2, 3)

In [98]:
x[:2,1]

array([2, 5])

In [99]:
x.size

6

In [100]:
x.ndim

2

In [106]:
w=np.arange(0,30,3)
print(w)

[ 0  3  6  9 12 15 18 21 24 27]


In [108]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [113]:
np.linspace(1,10,19)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [114]:
w=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [10,11,12,23]
    
])

In [116]:
w.shape

(3, 4)

In [123]:
w.sum(axis=1)

array([10, 26, 56])

In [126]:
w.min(axis=0)

array([1, 2, 3, 4])

In [130]:
np.sort(w,axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 23]])